### ISSUE TITLE
Upgrade to SQLAlchemy 2.0 once it moves out of beta

### ISSUE THREAD

**Issue by lorenyu** [navapbc/template-application-flask#82]

**Comment by Nava-JoshLong** [comment]
Using the version in main, the app builds fine, upgrading past it to 2.X causes errors. One of them is the following

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/src/db/migrations/run.py", line 23, in up
    command.upgrade(alembic_cfg, revision)
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/db/migrations/env.py", line 20, in <module>
    from src.db.models import metadata  # noqa: E402 isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/db/models/__init__.py", line 3, in <module>
    from . import base, user_models
  File "/app/src/db/models/user_models.py", line 21, in <module>
    class User(Base, IdMixin, TimestampMixin):
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 199, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 786, in _scan_attributes
    locally_collected_columns = self._produce_column_copies(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1331, in _produce_column_copies
    collected_annotation = self._collect_annotation(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1233, in _collect_annotation
    extracted = _extract_mapped_subtype(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshlong/.cache/pypoetry/virtualenvs/template-application-flask-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/util.py", line 2365, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "User.id" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
```

The other, which isn't always popping up so it could be another version issue, is [this line](https://github.com/navapbc/template-application-flask/blob/main/app/src/adapters/db/clients/postgres_client.py#L60). Looks like the module changes where dbapi_connection is located

**Comment by lorenyu** [comment]
released this january https://www.sqlalchemy.org/blog/2023/01/26/sqlalchemy-2.0.0-released/ so i'll remove waiting label now
